#include "eaf_test.h"
#include "lv_eaf.h"

/* Embedded EAF file - symbols generated by EMBED_TXTFILES */
extern const uint8_t eaf_eaf_test_start[] asm("_binary_eaf_test_eaf_start");
extern const uint8_t eaf_eaf_test_end[]   asm("_binary_eaf_test_eaf_end");

static lv_image_dsc_t s_test_eaf_dsc;

#define TAG   "eaf test"

void eaf_ui_screen_init(lv_obj_t *parent)
{
    bsp_display_lock(-1);

    /* Initialize embedded EAF image descriptor */
    size_t eaf_size = eaf_eaf_test_start - eaf_eaf_test_end;
    ESP_LOGI(TAG, "Embedded EAF size: %d bytes", eaf_size);

    s_test_eaf_dsc.header.magic = LV_IMAGE_HEADER_MAGIC;
    s_test_eaf_dsc.header.cf = LV_COLOR_FORMAT_RAW;
    s_test_eaf_dsc.header.flags = 0;
    s_test_eaf_dsc.header.w = 1;
    s_test_eaf_dsc.header.h = 1;
    s_test_eaf_dsc.header.stride = 0;
    s_test_eaf_dsc.header.reserved_2 = 0;
    s_test_eaf_dsc.data_size = eaf_size;
    s_test_eaf_dsc.data = eaf_eaf_test_start;

    lv_obj_t *anim = lv_eaf_create(parent);

    lv_eaf_set_src(anim, &s_test_eaf_dsc);
    lv_eaf_is_loaded(anim);
    lv_obj_center(anim);
    int32_t total_frames = lv_eaf_get_total_frames(anim);
    ESP_LOGI(TAG, "Total frames: %d", total_frames);

    bsp_display_unlock();
}